-- MySQL Script generated by MySQL Workbench
-- 02/03/16 21:10:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LingoLynx
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LingoLynx` ;

-- -----------------------------------------------------
-- Schema LingoLynx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LingoLynx` DEFAULT CHARACTER SET utf8 ;
USE `LingoLynx` ;

-- -----------------------------------------------------
-- Table `LingoLynx`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LingoLynx`.`User` ;

CREATE TABLE IF NOT EXISTS `LingoLynx`.`User` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `isActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LingoLynx`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LingoLynx`.`Comment` ;

CREATE TABLE IF NOT EXISTS `LingoLynx`.`Comment` (
  `idComment` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUser` INT UNSIGNED NOT NULL,
  `idSentence` INT UNSIGNED NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `likes` INT NULL,
  `dislikes` INT NULL,
  `isHidden` TINYINT(1) NULL,
  PRIMARY KEY (`idComment`),
  UNIQUE INDEX `idComment_UNIQUE` (`idComment` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `LingoLynx`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LingoLynx`.`Deck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LingoLynx`.`Deck` ;

CREATE TABLE IF NOT EXISTS `LingoLynx`.`Deck` (
  `idDeck` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUser` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `isPublic` TINYINT(1) NULL,
  `isHidden` TINYINT(1) NULL,
  PRIMARY KEY (`idDeck`),
  UNIQUE INDEX `idDeck_UNIQUE` (`idDeck` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `fk_userid_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `LingoLynx`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LingoLynx`.`Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LingoLynx`.`Language` ;

CREATE TABLE IF NOT EXISTS `LingoLynx`.`Language` (
  `idLanguage` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `englishName` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `isActive` VARCHAR(45) BINARY NULL,
  PRIMARY KEY (`idLanguage`),
  UNIQUE INDEX `idLanguage_UNIQUE` (`idLanguage` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LingoLynx`.`SentenceDeck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LingoLynx`.`SentenceDeck` ;

CREATE TABLE IF NOT EXISTS `LingoLynx`.`SentenceDeck` (
  `idSentenceDeck` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idSentence` INT UNSIGNED NOT NULL,
  `idDeck` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSentenceDeck`),
  INDEX `idDeck_idx` (`idDeck` ASC),
  CONSTRAINT `idDeck`
    FOREIGN KEY (`idDeck`)
    REFERENCES `LingoLynx`.`Deck` (`idDeck`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
